name: CI Checks
on:
  - pull_request
  - workflow_dispatch

jobs:
  deployment:
    needs: validate-tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate tags
        uses: ./.github/actions/tags-on-main
        id: validate-tags

      - name: Check exit
        if: ${{ steps.validate-tags.outputs.tagsexist == 'false' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Deployment tags are not on main branch!')
