name: CI Checks
on:
  - pull_request
  - workflow_dispatch

jobs:
  validate-tags:
    name: Validate deployment tags
    runs-on: ubuntu-latest
    outputs:
      tagsexist: ${{ steps.validate-tags.outputs.tagsexist }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate tags
        uses: ./.github/actions/tags-on-main
        id: validate-tags

  deployment:
    needs: validate-tags
    runs-on: ubuntu-latest

    steps:
      - name: Check exit
        if: ${{ needs.validate-tags.outputs.tagsexist }} == "false"
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Deployment tags are not on main branch!')

      - name: Checkout code
        uses: actions/checkout@v4
